name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # build-java17:
  #   name: Build with Java 17
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'

  #     - name: Verify Java version
  #       run: java -version

  #     - name: Build with Maven (Java 17)
  #       run: mvn clean install

  build-java21:
    name: Build with Java 21
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Verify Java version
        run: java -version

      - name: Build with Maven (Java 21)
        run: mvn clean install
